### PR TITLE
Changed the naming of custom Header class files

### PR DESCRIPTION
**Pull request by tmedwards**
Changed the naming of custom Header class files from `%header%/%header%.py` to `%header%/header.py` in order to fix the issue where if a user renames the story format's directory, the custom Header file will no longer be found (since it currently is based on the name of the directory, rather than having a constant name).

### CODE REVIEW

**Comment by webbedspace** [comment]
Shouldn't this rename all of the built-in formats' header class files, too?

**Comment by tmedwards** [comment]
It should, yes.  I was under the impression they didn't specify custom Header class files, but I see now I was mistaken.  I'll go ahead and get those renamed and update the PR.

**Comment by tmedwards** [comment]
Done.

**Comment by webbedspace** [comment]
Thinking about it more... I know there's probably not that many other formats out there but I think we might as well keep the extant ones working, by attempting to open `%header%/%header%.py` as a fallback if `header.py` is not present.

**Comment by tmedwards** [comment]
Sensible, and done.

**Pull request merged**
